import type { AcademySubject } from '../../../../types/academy'

export const CS_SUBJECT: AcademySubject = {
  id: 'computer_science',
  title: 'Computer Science & Coding',
  tagline: 'Algorithms, Sequencing, Loops & Computational Logic',
  description: 'Program autonomous robots, design step-by-step algorithms, use repeat loops to solve mazes, and debug logic puzzles.',
  icon: '💻',
  accentColor: '#0ea5e9',
  heroGradient: 'linear-gradient(135deg, #075985 0%, #0284c7 50%, #38bdf8 100%)',
  cognitiveDomain: 'logic',
  courses: [
    {
      id: 'cs_algorithms_sequencing',
      subjectId: 'computer_science',
      title: 'Algorithmic Sequencing & Directional Logic',
      tagline: 'Step-by-step instructions for BEEP-0',
      description: 'Break complex problems into clear, ordered instructions.',
      icon: '🤖',
      ageBand: 'beginner',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_sequential_commands',
          courseId: 'cs_algorithms_sequencing',
          subjectId: 'computer_science',
          orderIndex: 1,
          title: 'Precise Sequences & Turns',
          description: 'Understanding order of execution.',
          icon: '➡️',
          skills: [
            {
              id: 'skill_directional_steps',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 1,
              title: 'Directional Robot Steps',
              description: 'Guide robots one tile at a time with Forward and Turn commands.',
              icon: '🤖',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_k_robot_steps',
              practiceSetId: 'practice_directional_steps',
              capstoneGameId: 'robopath',
            },
            {
              id: 'skill_algorithmic_patterns_g1',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 2,
              title: 'Repeating Algorithmic Patterns',
              description: 'Recognize and extend repeating code and symbol sequences.',
              icon: '🔁',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_directional_steps'],
              lessonId: 'lesson_g1_pattern_repeats',
              practiceSetId: 'practice_algorithmic_patterns_g1',
              capstoneGameId: 'robopath',
            },
            {
              id: 'skill_step_sequencing',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 3,
              title: 'Command Sequencing',
              description: 'Chain Forward, Turn Left, and Turn Right commands to navigate a grid without hitting obstacles.',
              icon: '🧭',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_algorithmic_patterns_g1'],
              lessonId: 'lesson_sequencing',
              practiceSetId: 'practice_sequencing',
              capstoneGameId: 'robopath',
            },
            {
              id: 'skill_loops_repetition',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 4,
              title: 'Repeat Loops & Efficiency',
              description: 'Use Repeat N Times tokens to write cleaner code and beat par move limits.',
              icon: '🔁',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_step_sequencing'],
              lessonId: 'lesson_loops',
              practiceSetId: 'practice_loops',
              capstoneGameId: 'robopath',
            },
            {
              id: 'skill_debugging_commands',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 5,
              title: 'Robot Routine Debugging',
              description: 'Identify and fix bugs, wrong turns, and incorrect sequences in robot code routines.',
              icon: '🐛',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_algorithmic_patterns_g1'],
              lessonId: 'lesson_g3_debugging_commands',
              practiceSetId: 'practice_debugging_commands',
              capstoneGameId: 'robopath',
            },
            {
              id: 'skill_conditional_if_else',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 6,
              title: 'Conditional Branching: IF / ELSE',
              description: 'Make robots react dynamically to sensor obstacles using IF obstacle THEN turn ELSE move forward.',
              icon: '🔀',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_debugging_commands'],
              lessonId: 'lesson_g4_conditional_if_else',
              practiceSetId: 'practice_conditional_if_else',
              capstoneGameId: 'robopath',
            },
            {
              id: 'skill_algorithmic_efficiency',
              unitId: 'unit_sequential_commands',
              courseId: 'cs_algorithms_sequencing',
              subjectId: 'computer_science',
              orderIndex: 7,
              title: 'Algorithmic Efficiency & Nested Loops',
              description: 'Optimize nested repetition loops to solve large maze matrices in minimal operations.',
              icon: '⚡',
              ageBand: 'advanced',
              prerequisiteSkillIds: ['skill_conditional_if_else'],
              lessonId: 'lesson_g6_algorithmic_efficiency',
              practiceSetId: 'practice_algorithmic_efficiency',
              capstoneGameId: 'robopath',
            },
          ],
        },
      ],
    },
  ],
}
