import type { AcademySubject } from '../../../../types/academy'

export const ENGLISH_SUBJECT: AcademySubject = {
  id: 'english',
  title: 'English & Language Arts',
  tagline: 'Phonics, Storytelling, Morphology & Grammar',
  description: 'Master phonetic rhythms, forge root morphemes on ancient anvils, comprehend rich story arcs, and craft expressive sentences.',
  icon: '📚',
  accentColor: '#a855f7',
  heroGradient: 'linear-gradient(135deg, #6b21a8 0%, #7e22ce 50%, #a855f7 100%)',
  cognitiveDomain: 'vocabulary',
  courses: [
    {
      id: 'english_phonics_rhythm',
      subjectId: 'english',
      title: 'Phonics & Syllable Rhythms',
      tagline: 'Letter sounds, blends, digraphs & musical syllables',
      description: 'Connect spoken phonemes to written letters and clap out syllable beats.',
      icon: '🎵',
      ageBand: 'beginner',
      estimatedMinutes: 40,
      units: [
        {
          id: 'unit_syllable_rhythms',
          courseId: 'english_phonics_rhythm',
          subjectId: 'english',
          orderIndex: 1,
          title: 'Syllables & Sound Beats',
          description: 'Break words into melodic beats.',
          icon: '🥁',
          skills: [
            {
              id: 'skill_phonics_prek',
              unitId: 'unit_syllable_rhythms',
              courseId: 'english_phonics_rhythm',
              subjectId: 'reading',
              orderIndex: 1,
              title: 'Animal Sounds & Early Phonics',
              description: 'Match creature voices and develop early auditory discrimination.',
              icon: '🐱',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_prek_animal_sounds',
              practiceSetId: 'practice_phonics_prek',
            },
            {
              id: 'skill_rhyme_patterns',
              unitId: 'unit_syllable_rhythms',
              courseId: 'english_phonics_rhythm',
              subjectId: 'reading',
              orderIndex: 2,
              title: 'Rhyming Word Patterns',
              description: 'Identify rhyming word family endings like -AT, -OG, -UG.',
              icon: '✨',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_phonics_prek'],
              lessonId: 'lesson_k_rhyme_time',
              practiceSetId: 'practice_rhyme_patterns',
              capstoneGameId: 'spellforge',
            },
            {
              id: 'skill_sight_words_g1',
              unitId: 'unit_syllable_rhythms',
              courseId: 'english_phonics_rhythm',
              subjectId: 'reading',
              orderIndex: 3,
              title: 'High-Frequency Sight Words',
              description: 'Read essential golden sight words (THE, SAID, HAVE, WERE) fluently.',
              icon: '📜',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_rhyme_patterns'],
              lessonId: 'lesson_g1_sight_words',
              practiceSetId: 'practice_sight_words_g1',
              capstoneGameId: 'word_trace',
            },
            {
              id: 'skill_syllable_counting',
              unitId: 'unit_syllable_rhythms',
              courseId: 'english_phonics_rhythm',
              subjectId: 'english',
              orderIndex: 4,
              title: 'Counting Syllable Beats',
              description: 'Clap and tap the number of syllables in compound and multisyllabic words.',
              icon: '🎶',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_syllables',
              practiceSetId: 'practice_syllables',
              capstoneGameId: 'rhythm_spells',
            },
          ],
        },
      ],
    },
    {
      id: 'english_morphology_vocabulary',
      subjectId: 'english',
      title: 'Morphology & Root Words',
      tagline: 'Prefixes, suffixes, base words & word forging',
      description: 'Unlock thousands of words by understanding prefixes (un-, re-, pre-) and suffixes (-ful, -less, -tion).',
      icon: '🔥',
      ageBand: 'developing',
      estimatedMinutes: 60,
      units: [
        {
          id: 'unit_prefixes_suffixes',
          courseId: 'english_morphology_vocabulary',
          subjectId: 'english',
          orderIndex: 1,
          title: 'Word Forging: Prefixes & Suffixes',
          description: 'Assemble affixes to create new meanings.',
          icon: '🔨',
          skills: [
            {
              id: 'skill_prefix_un_re',
              unitId: 'unit_prefixes_suffixes',
              courseId: 'english_morphology_vocabulary',
              subjectId: 'english',
              orderIndex: 1,
              title: 'Prefixes: UN- and RE-',
              description: 'Learn how "un-" means NOT or OPPOSITE, and "re-" means AGAIN.',
              icon: '🔄',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_prefixes_un_re',
              practiceSetId: 'practice_prefixes_un_re',
              capstoneGameId: 'spellforge',
            },
            {
              id: 'skill_contextual_word_trace',
              unitId: 'unit_prefixes_suffixes',
              courseId: 'english_morphology_vocabulary',
              subjectId: 'english',
              orderIndex: 2,
              title: 'Context Clue Vocabulary',
              description: 'Decipher unfamiliar target words inside story paragraphs using semantic clues.',
              icon: '🔤',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_prefix_un_re'],
              lessonId: 'lesson_context_clues',
              practiceSetId: 'practice_context_clues',
              capstoneGameId: 'word_trace',
            },
          ],
        },
      ],
    },
  ],
}

export const READING_SUBJECT: AcademySubject = {
  id: 'reading',
  title: 'Reading Comprehension',
  tagline: 'Main Idea, Inferences & Character Motivation',
  description: 'Uncover deeper layers in stories, analyze character choices, and deduce evidence from text.',
  icon: '📖',
  accentColor: '#ec4899',
  heroGradient: 'linear-gradient(135deg, #9d174d 0%, #db2777 50%, #ec4899 100%)',
  cognitiveDomain: 'comprehension',
  courses: [
    {
      id: 'reading_inferences',
      subjectId: 'reading',
      title: 'Making Inferences & Finding Clues',
      tagline: 'Read between the lines like a detective',
      description: 'Combine text clues with background knowledge to draw conclusions.',
      icon: '🔎',
      ageBand: 'developing',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_text_evidence',
          courseId: 'reading_inferences',
          subjectId: 'reading',
          orderIndex: 1,
          title: 'Textual Clues & Deduction',
          description: 'Find proof in sentences.',
          icon: '📜',
          skills: [
            {
              id: 'skill_drawing_inferences',
              unitId: 'unit_text_evidence',
              courseId: 'reading_inferences',
              subjectId: 'reading',
              orderIndex: 1,
              title: 'Drawing Logical Inferences',
              description: 'Identify what a character is feeling even when the author does not explicitly say it.',
              icon: '🧐',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_inferences',
              practiceSetId: 'practice_inferences',
              capstoneGameId: 'mystery_detective',
            },
            {
              id: 'skill_story_main_idea',
              unitId: 'unit_text_evidence',
              courseId: 'reading_inferences',
              subjectId: 'reading',
              orderIndex: 2,
              title: 'Unlocking the Main Idea',
              description: 'Determine the central theme and supporting key details of a story scroll.',
              icon: '📜',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_sight_words_g1'],
              lessonId: 'lesson_g3_story_main_idea',
              practiceSetId: 'practice_story_main_idea',
              capstoneGameId: 'memory_museum',
            },
          ],
        },
      ],
    },
  ],
}

export const VOCABULARY_SUBJECT: AcademySubject = {
  id: 'vocabulary',
  title: 'Vocabulary & Etymology',
  tagline: 'Tier-2 Academic Words, Synonyms & Word Roots',
  description: 'Expand your magical lexicon with vivid descriptive vocabulary and Greek/Latin roots.',
  icon: '🗣️',
  accentColor: '#f59e0b',
  heroGradient: 'linear-gradient(135deg, #92400e 0%, #d97706 50%, #f59e0b 100%)',
  cognitiveDomain: 'vocabulary',
  courses: [
    {
      id: 'vocab_academic_tier2',
      subjectId: 'vocabulary',
      title: 'Descriptive & Academic Words',
      tagline: 'Powerful adjectives, verbs & nuanced expressions',
      description: 'Replace simple words with precise, evocative terminology.',
      icon: '✨',
      ageBand: 'developing',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_synonyms_shades',
          courseId: 'vocab_academic_tier2',
          subjectId: 'vocabulary',
          orderIndex: 1,
          title: 'Shades of Meaning & Synonyms',
          description: 'Rank words by intensity and tone.',
          icon: '🎨',
          skills: [
            {
              id: 'skill_shades_of_meaning',
              unitId: 'unit_synonyms_shades',
              courseId: 'vocab_academic_tier2',
              subjectId: 'vocabulary',
              orderIndex: 1,
              title: 'Shades of Meaning',
              description: 'Differentiate between "warm", "hot", and "scorching".',
              icon: '🌡️',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_shades_meaning',
              practiceSetId: 'practice_shades_meaning',
              capstoneGameId: 'word_trace',
            },
            {
              id: 'skill_prefixes_un_re_dis',
              unitId: 'unit_synonyms_shades',
              courseId: 'vocab_academic_tier2',
              subjectId: 'vocabulary',
              orderIndex: 2,
              title: 'Prefix Magic: UN-, RE-, DIS-',
              description: 'Attach prefixes to transform base words on the linguistic forge anvil.',
              icon: '🔨',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_prefix_un_re'],
              lessonId: 'lesson_g4_prefixes_un_re_dis',
              practiceSetId: 'practice_prefixes_un_re_dis',
              capstoneGameId: 'spellforge',
            },
            {
              id: 'skill_shades_of_meaning_tier2',
              unitId: 'unit_synonyms_shades',
              courseId: 'vocab_academic_tier2',
              subjectId: 'vocabulary',
              orderIndex: 3,
              title: 'Nuanced Adjectives & Shades of Meaning',
              description: 'Rank emotive adjectives and nuanced descriptors by psychological intensity.',
              icon: '🌈',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_prefixes_un_re_dis'],
              lessonId: 'lesson_g5_shades_of_meaning_tier2',
              practiceSetId: 'practice_shades_of_meaning_tier2',
              capstoneGameId: 'spellforge',
            },
          ],
        },
      ],
    },
  ],
}

export const GRAMMAR_SUBJECT: AcademySubject = {
  id: 'grammar',
  title: 'Grammar & Syntax',
  tagline: 'Parts of Speech, Sentence Structures & Punctuation',
  description: 'Craft elegant sentences with nouns, action verbs, vivid modifiers, and punctuation mastery.',
  icon: '✍️',
  accentColor: '#06b6d4',
  heroGradient: 'linear-gradient(135deg, #155e75 0%, #0891b2 50%, #06b6d4 100%)',
  cognitiveDomain: 'vocabulary',
  courses: [
    {
      id: 'grammar_parts_of_speech',
      subjectId: 'grammar',
      title: 'Parts of Speech Kingdom',
      tagline: 'Nouns, Verbs, Adjectives & Adverbs',
      description: 'Discover the distinct roles words play in constructing complete thoughts.',
      icon: '🏰',
      ageBand: 'beginner',
      estimatedMinutes: 40,
      units: [
        {
          id: 'unit_nouns_verbs',
          courseId: 'grammar_parts_of_speech',
          subjectId: 'grammar',
          orderIndex: 1,
          title: 'Nouns & Action Verbs',
          description: 'People, places, things, and actions.',
          icon: '🏃',
          skills: [
            {
              id: 'skill_nouns_g1',
              unitId: 'unit_nouns_verbs',
              courseId: 'grammar_parts_of_speech',
              subjectId: 'grammar',
              orderIndex: 1,
              title: 'Naming Nouns: People, Places & Things',
              description: 'Spot nouns that name persons, magical places, or creature friends in sentences.',
              icon: '🏰',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_g1_noun_detective',
              practiceSetId: 'practice_nouns_g1',
              capstoneGameId: 'spellforge',
            },
            {
              id: 'skill_identifying_verbs',
              unitId: 'unit_nouns_verbs',
              courseId: 'grammar_parts_of_speech',
              subjectId: 'grammar',
              orderIndex: 2,
              title: 'Identifying Action Verbs',
              description: 'Spot words that show physical or mental action in sentences.',
              icon: '⚡',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_nouns_g1'],
              lessonId: 'lesson_action_verbs',
              practiceSetId: 'practice_action_verbs',
            },
            {
              id: 'skill_compound_words',
              unitId: 'unit_nouns_verbs',
              courseId: 'grammar_parts_of_speech',
              subjectId: 'grammar',
              orderIndex: 3,
              title: 'Compound Word Chemistry',
              description: 'Combine two independent nouns into powerful compound runes like SUN + FLOWER = SUNFLOWER.',
              icon: '🌻',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_nouns_g1'],
              lessonId: 'lesson_g2_compound_words',
              practiceSetId: 'practice_compound_words',
              capstoneGameId: 'spellforge',
            },
          ],
        },
      ],
    },
  ],
}
