import type { AcademySubject } from '../../../../types/academy'

export const LOGIC_SUBJECT: AcademySubject = {
  id: 'logic',
  title: 'Deductive Logic & Puzzles',
  tagline: 'Constraint Elimination, Patterns & Whodunit Reasoning',
  description: 'Analyze clues, use deductive matrices, eliminate false suspects, and solve spatial pattern puzzles.',
  icon: '🔍',
  accentColor: '#6366f1',
  heroGradient: 'linear-gradient(135deg, #3730a3 0%, #4f46e5 50%, #6366f1 100%)',
  cognitiveDomain: 'logic',
  courses: [
    {
      id: 'logic_deduction_elimination',
      subjectId: 'logic',
      title: 'Forensic Deduction & Elimination',
      tagline: 'Solving mysteries through logic grids and alibis',
      description: 'Collect physical clues, analyze witness statements, and eliminate impossible culprits.',
      icon: '🕵️',
      ageBand: 'developing',
      estimatedMinutes: 50,
      units: [
        {
          id: 'unit_clue_analysis',
          courseId: 'logic_deduction_elimination',
          subjectId: 'logic',
          orderIndex: 1,
          title: 'Evidence Evaluation',
          description: 'Distinguish direct facts from assumptions.',
          icon: '📋',
          skills: [
            {
              id: 'skill_suspect_elimination',
              unitId: 'unit_clue_analysis',
              courseId: 'logic_deduction_elimination',
              subjectId: 'logic',
              orderIndex: 1,
              title: 'Process of Elimination',
              description: 'Rule out suspects systematically when their traits or alibis contradict evidence.',
              icon: '❌',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_elimination',
              practiceSetId: 'practice_elimination',
              capstoneGameId: 'mystery_detective',
            },
            {
              id: 'skill_inference_clues',
              unitId: 'unit_clue_analysis',
              courseId: 'logic_deduction_elimination',
              subjectId: 'logic',
              orderIndex: 2,
              title: 'Textual Clues & Inference',
              description: 'Piece together subtle character behaviors and forensic evidence.',
              icon: '🔍',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_suspect_elimination'],
              lessonId: 'lesson_g4_inference_clues',
              practiceSetId: 'practice_inference_clues',
              capstoneGameId: 'memory_museum',
            },
            {
              id: 'skill_deduction_grid_matrix',
              unitId: 'unit_clue_analysis',
              courseId: 'logic_deduction_elimination',
              subjectId: 'logic',
              orderIndex: 3,
              title: 'Forensic Deduction Grid Matrix',
              description: 'Solve 3x3 alibi elimination matrices using multiple intersecting logic rules.',
              icon: '📊',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_inference_clues'],
              lessonId: 'lesson_g5_deduction_grid_matrix',
              practiceSetId: 'practice_deduction_grid_matrix',
              capstoneGameId: 'memory_museum',
            },
          ],
        },
      ],
    },
  ],
}

export const CREATIVITY_SUBJECT: AcademySubject = {
  id: 'creativity',
  title: 'Creativity & World Design',
  tagline: 'Spatial Design, Prototyping & Ecological Balance',
  description: 'Build floating island biomes, prototype kinetic contraptions, and invent creative solutions to engineering challenges.',
  icon: '🎨',
  accentColor: '#f43f5e',
  heroGradient: 'linear-gradient(135deg, #9f1239 0%, #e11d48 50%, #f43f5e 100%)',
  cognitiveDomain: 'creativity',
  courses: [
    {
      id: 'creativity_biome_design',
      subjectId: 'creativity',
      title: 'Ecological World Crafting',
      tagline: 'Designing balanced habitats and sanctuaries',
      description: 'Place terrain elements, water channels, and flora to attract diverse wildlife.',
      icon: '🏝️',
      ageBand: 'developing',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_spatial_harmony',
          courseId: 'creativity_biome_design',
          subjectId: 'creativity',
          orderIndex: 1,
          title: 'Spatial Habitat Harmony',
          description: 'Balance natural biomes.',
          icon: '🌺',
          skills: [
            {
              id: 'skill_color_sorting_prek',
              unitId: 'unit_spatial_harmony',
              courseId: 'creativity_biome_design',
              subjectId: 'creativity',
              orderIndex: 1,
              title: 'Primary Color Gem Sorting',
              description: 'Sort glowing red, blue, and yellow star crystals into cosmic baskets.',
              icon: '🎨',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_prek_color_sorting',
              practiceSetId: 'practice_color_sorting_prek',
            },
            {
              id: 'skill_biome_creation',
              unitId: 'unit_spatial_harmony',
              courseId: 'creativity_biome_design',
              subjectId: 'creativity',
              orderIndex: 2,
              title: 'Creating Sanctuary Habitats',
              description: 'Discover how clustering forest and water tiles attracts rare magical fauna.',
              icon: '🦌',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_biome_design',
              practiceSetId: 'practice_biome_design',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_musical_dynamics',
              unitId: 'unit_spatial_harmony',
              courseId: 'creativity_biome_design',
              subjectId: 'creativity',
              orderIndex: 3,
              title: 'Piano & Forte Musical Dynamics',
              description: 'Distinguish soft whisper tones (piano) and booming energy surges (forte).',
              icon: '🎹',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_color_sorting_prek'],
              lessonId: 'lesson_g2_musical_dynamics',
              practiceSetId: 'practice_musical_dynamics',
              capstoneGameId: 'rhythm_spells',
            },
          ],
        },
      ],
    },
  ],
}

export const GENERAL_KNOWLEDGE_SUBJECT: AcademySubject = {
  id: 'general_knowledge',
  title: 'World Discovery & Wonders',
  tagline: 'Earth Wonders, Inventions & Cosmic History',
  description: 'Uncover how great inventions were created, explore natural marvels of Earth, and journey through cosmic milestones.',
  icon: '🌍',
  accentColor: '#14b8a6',
  heroGradient: 'linear-gradient(135deg, #115e59 0%, #0d9488 50%, #14b8a6 100%)',
  cognitiveDomain: 'comprehension',
  courses: [
    {
      id: 'gk_great_inventions',
      subjectId: 'general_knowledge',
      title: 'The Story of Great Inventions',
      tagline: 'From the wheel to telescopes and flight',
      description: 'Learn how humans solved monumental challenges with curiosity and ingenuity.',
      icon: '💡',
      ageBand: 'developing',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_historical_tools',
          courseId: 'gk_great_inventions',
          subjectId: 'general_knowledge',
          orderIndex: 1,
          title: 'Tools of Exploration & Body Awareness',
          description: 'Compasses, balances, breathing awareness, and optics.',
          icon: '🔭',
          skills: [
            {
              id: 'skill_sel_belly_breathing',
              unitId: 'unit_historical_tools',
              courseId: 'gk_great_inventions',
              subjectId: 'general_knowledge',
              orderIndex: 1,
              title: 'Balloon Belly Breathing',
              description: 'Practice slow rhythmic belly breathing for bodily calm and peaceful focus.',
              icon: '🎈',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_prek_belly_breathing',
              practiceSetId: 'practice_sel_belly_breathing',
            },
            {
              id: 'skill_optics_lenses',
              unitId: 'unit_historical_tools',
              courseId: 'gk_great_inventions',
              subjectId: 'general_knowledge',
              orderIndex: 2,
              title: 'Light, Lenses & Telescopes',
              description: 'Understand how curved glass refracts light to reveal distant planets and tiny microbes.',
              icon: '🔬',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_optics_lenses',
              practiceSetId: 'practice_optics_lenses',
              capstoneGameId: 'cosmic_constellations',
            },
            {
              id: 'skill_scientific_hypothesis',
              unitId: 'unit_historical_tools',
              courseId: 'gk_great_inventions',
              subjectId: 'general_knowledge',
              orderIndex: 3,
              title: 'The Scientific Method & Falsifiable Hypotheses',
              description: 'Formulate predictive hypotheses and test evidence against empirical observations.',
              icon: '🧭',
              ageBand: 'advanced',
              prerequisiteSkillIds: ['skill_optics_lenses'],
              lessonId: 'lesson_g6_scientific_hypothesis',
              practiceSetId: 'practice_scientific_hypothesis',
              capstoneGameId: 'sanctuary',
            },
          ],
        },
      ],
    },
  ],
}
