import type { AcademySubject } from '../../../../types/academy'

export const MATH_SUBJECT: AcademySubject = {
  id: 'math',
  title: 'Mathematics',
  tagline: 'Crystal Geometry, Numbers & Algebraic Intuition',
  description: 'Explore counting constellations, master addition & subtraction spells, balance algebraic potion scales, and uncover the symmetry of geometric worlds.',
  icon: '📐',
  accentColor: '#38bdf8',
  heroGradient: 'linear-gradient(135deg, #0369a1 0%, #0284c7 50%, #38bdf8 100%)',
  cognitiveDomain: 'logic',
  courses: [
    {
      id: 'math_numbers_counting',
      subjectId: 'math',
      title: 'Numbers, Quantities & Place Value',
      tagline: 'Discover the power of numbers 1 to 100',
      description: 'Understand counting, number lines, tens and ones place value, and even/odd patterns.',
      icon: '🔢',
      ageBand: 'beginner',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_counting_within_20',
          courseId: 'math_numbers_counting',
          subjectId: 'math',
          orderIndex: 1,
          title: 'Counting & Number Sense Within 20',
          description: 'Visualize quantities using ten-frames and number lines.',
          icon: '✨',
          skills: [
            {
              id: 'skill_shapes_prek',
              unitId: 'unit_counting_within_20',
              courseId: 'math_numbers_counting',
              subjectId: 'math',
              orderIndex: 1,
              title: 'Star Shape Constellations',
              description: 'Identify circles, triangles, and squares in the night sky.',
              icon: '🔺',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_prek_shape_constellations',
              practiceSetId: 'practice_shapes_prek',
            },
            {
              id: 'skill_comparison_prek',
              unitId: 'unit_counting_within_20',
              courseId: 'math_numbers_counting',
              subjectId: 'math',
              orderIndex: 2,
              title: 'Big vs Small Scale',
              description: 'Compare giant celestial objects and tiny stardust pebbles.',
              icon: '🐘',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_prek_big_small',
              practiceSetId: 'practice_comparison_prek',
            },
            {
              id: 'skill_ten_frames',
              unitId: 'unit_counting_within_20',
              courseId: 'math_numbers_counting',
              subjectId: 'math',
              orderIndex: 3,
              title: 'Mastering Ten-Frames',
              description: 'Recognize quantities instantly with visual ten-frame grids.',
              icon: '🔟',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_ten_frames',
              practiceSetId: 'practice_ten_frames',
            },
            {
              id: 'skill_counting_to_10',
              unitId: 'unit_counting_within_20',
              courseId: 'math_numbers_counting',
              subjectId: 'math',
              orderIndex: 4,
              title: 'Counting to 10 on Altar Frames',
              description: 'Fill 5 top and 5 bottom moonstones to complete 10.',
              icon: '🌟',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_ten_frames'],
              lessonId: 'lesson_k_counting_10',
              practiceSetId: 'practice_counting_to_10',
              capstoneGameId: 'potion_scales',
            },
            {
              id: 'skill_number_lines_20',
              unitId: 'unit_counting_within_20',
              courseId: 'math_numbers_counting',
              subjectId: 'math',
              orderIndex: 5,
              title: 'Jumping on the Number Line',
              description: 'Count forward and backward along magical stepping stones.',
              icon: '📏',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_ten_frames'],
              lessonId: 'lesson_number_lines_20',
              practiceSetId: 'practice_number_lines_20',
            },
            {
              id: 'skill_place_value_tens_ones',
              unitId: 'unit_counting_within_20',
              courseId: 'math_numbers_counting',
              subjectId: 'math',
              orderIndex: 6,
              title: 'Place Value: Tens and Ones',
              description: 'Bundle star crystals into groups of ten and single ones.',
              icon: '💎',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_number_lines_20'],
              lessonId: 'lesson_g2_place_value_tens',
              practiceSetId: 'practice_place_value_tens_ones',
              capstoneGameId: 'magic_machine',
            },
          ],
        },
      ],
    },
    {
      id: 'math_operations',
      subjectId: 'math',
      title: 'Addition & Subtraction Magic',
      tagline: 'Combining and comparing quantities',
      description: 'Master facts within 20, regrouping strategies, and word problem reasoning.',
      icon: '➕',
      ageBand: 'developing',
      estimatedMinutes: 60,
      units: [
        {
          id: 'unit_addition_facts_20',
          courseId: 'math_operations',
          subjectId: 'math',
          orderIndex: 1,
          title: 'Addition & Subtraction Within 20',
          description: 'Making tens, doubles, and friendly number jumps.',
          icon: '🌟',
          skills: [
            {
              id: 'skill_number_lines_subtraction',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 1,
              title: 'Backward Hopping Subtraction',
              description: 'Hop leftward on number lines to solve equations like 10 - 4 = 6.',
              icon: '🔙',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_number_lines_20'],
              lessonId: 'lesson_g1_subtraction_jumps',
              practiceSetId: 'practice_subtraction_jumps',
              capstoneGameId: 'potion_scales',
            },
            {
              id: 'skill_fair_sharing_division',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 2,
              title: 'Fair Sharing & Equal Groups',
              description: 'Distribute treats equally among animal friends.',
              icon: '🍎',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_counting_to_10'],
              lessonId: 'lesson_k_sharing_fair',
              practiceSetId: 'practice_sharing_fair',
            },
            {
              id: 'skill_making_ten_strategy',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 3,
              title: 'The Make-a-Ten Strategy',
              description: 'Decompose numbers to make an easy ten first (e.g. 8 + 5 = 8 + 2 + 3 = 13).',
              icon: '💫',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_make_ten',
              practiceSetId: 'practice_make_ten',
            },
            {
              id: 'skill_potion_balance_equations',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 4,
              title: 'Balance Scale Equations',
              description: 'Understand that the equals sign (=) means both sides have the same weight.',
              icon: '⚖️',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_making_ten_strategy'],
              lessonId: 'lesson_balance_equations',
              practiceSetId: 'practice_balance_equations',
              capstoneGameId: 'potion_scales',
            },
            {
              id: 'skill_arrays_multiplication_intro',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 5,
              title: 'Star Arrays & Repeated Addition',
              description: 'Organize star crystals into equal rows and columns to discover multiplication.',
              icon: '✨',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_number_lines_subtraction'],
              lessonId: 'lesson_g2_array_multiplication',
              practiceSetId: 'practice_arrays_multiplication_intro',
              capstoneGameId: 'magic_machine',
            },
            {
              id: 'skill_multiplication_arrays_g3',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 6,
              title: 'Multi-Row Multiplication Arrays',
              description: 'Calculate larger rectangular crystal arrays using repeated row addition.',
              icon: '📐',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_arrays_multiplication_intro'],
              lessonId: 'lesson_g3_multiplication_arrays',
              practiceSetId: 'practice_multiplication_arrays_g3',
              capstoneGameId: 'magic_machine',
            },
            {
              id: 'skill_balance_equations_intro',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 7,
              title: 'Balancing Equations & Unknowns',
              description: 'Solve for missing values (x + 7 = 15) using balance scales.',
              icon: '⚖️',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_multiplication_arrays_g3'],
              lessonId: 'lesson_g4_balance_equations_intro',
              practiceSetId: 'practice_balance_equations_intro',
              capstoneGameId: 'potion_scales',
            },
            {
              id: 'skill_algebraic_expressions',
              unitId: 'unit_addition_facts_20',
              courseId: 'math_operations',
              subjectId: 'math',
              orderIndex: 8,
              title: 'Algebraic Expressions & Variables',
              description: 'Substitute values into expressions like 2n + 5 to solve variable formulas.',
              icon: '🔮',
              ageBand: 'advanced',
              prerequisiteSkillIds: ['skill_balance_equations_intro'],
              lessonId: 'lesson_g6_algebraic_expressions',
              practiceSetId: 'practice_algebraic_expressions',
              capstoneGameId: 'magic_machine',
            },
          ],
        },
      ],
    },
    {
      id: 'math_fractions_ratios',
      subjectId: 'math',
      title: 'Fractions & Proportions',
      tagline: 'Equal parts, halves, fourths & ratios',
      description: 'Explore parts of a whole, fraction strips, and liquid ratios.',
      icon: '🥧',
      ageBand: 'intermediate',
      estimatedMinutes: 60,
      units: [
        {
          id: 'unit_equal_parts',
          courseId: 'math_fractions_ratios',
          subjectId: 'math',
          orderIndex: 1,
          title: 'Visualizing Fractions',
          description: 'Understanding numerators and denominators as parts and wholes.',
          icon: '🍕',
          skills: [
            {
              id: 'skill_fraction_parts_whole',
              unitId: 'unit_equal_parts',
              courseId: 'math_fractions_ratios',
              subjectId: 'math',
              orderIndex: 1,
              title: 'Parts of a Whole',
              description: 'Identify halves, thirds, and fourths on shapes and potion beakers.',
              icon: '🧪',
              ageBand: 'intermediate',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_fractions_intro',
              practiceSetId: 'practice_fractions_intro',
              capstoneGameId: 'potion_scales',
            },
            {
              id: 'skill_fraction_halves_fourths',
              unitId: 'unit_equal_parts',
              courseId: 'math_fractions_ratios',
              subjectId: 'math',
              orderIndex: 2,
              title: 'Fraction Halves, Thirds & Fourths',
              description: 'Partition potion bars and pizzas into equal fractional parts.',
              icon: '🥧',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_fair_sharing_division'],
              lessonId: 'lesson_g3_fraction_halves_fourths',
              practiceSetId: 'practice_fraction_halves_fourths',
              capstoneGameId: 'potion_scales',
            },
            {
              id: 'skill_fraction_multiplication',
              unitId: 'unit_equal_parts',
              courseId: 'math_fractions_ratios',
              subjectId: 'math',
              orderIndex: 3,
              title: 'Multiplying Unit Fractions with Area Grids',
              description: 'Multiply fractions visually using overlapping grid area models.',
              icon: '🔲',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_fraction_halves_fourths'],
              lessonId: 'lesson_g5_fraction_multiplication',
              practiceSetId: 'practice_fraction_multiplication',
              capstoneGameId: 'magic_machine',
            },
            {
              id: 'skill_ratios_proportions',
              unitId: 'unit_equal_parts',
              courseId: 'math_fractions_ratios',
              subjectId: 'math',
              orderIndex: 4,
              title: 'Alchemical Ratios & Proportions',
              description: 'Mix potion recipes using 2:3 reagent ratios and proportional scaling.',
              icon: '⚗️',
              ageBand: 'advanced',
              prerequisiteSkillIds: ['skill_fraction_multiplication'],
              lessonId: 'lesson_g6_ratios_proportions',
              practiceSetId: 'practice_ratios_proportions',
              capstoneGameId: 'potion_scales',
            },
          ],
        },
      ],
    },
  ],
}
