import type { AcademySubject } from '../../../../types/academy'

export const SCIENCE_SUBJECT: AcademySubject = {
  id: 'science',
  title: 'Science & Nature',
  tagline: 'Living Ecosystems, Physics Forces & Astronomy',
  description: 'Investigate biological food webs, test gravity & mechanical forces in physics workshops, and chart celestial constellations across deep space.',
  icon: '🔬',
  accentColor: '#10b981',
  heroGradient: 'linear-gradient(135deg, #065f46 0%, #059669 50%, #10b981 100%)',
  cognitiveDomain: 'logic',
  courses: [
    {
      id: 'science_ecosystems',
      subjectId: 'science',
      title: 'Living Ecosystems & Habitats',
      tagline: 'Producers, consumers, and balanced food webs',
      description: 'Discover how sunlight, plants, herbivores, and predators sustain living island biomes.',
      icon: '🌲',
      ageBand: 'beginner',
      estimatedMinutes: 50,
      units: [
        {
          id: 'unit_food_chains',
          courseId: 'science_ecosystems',
          subjectId: 'science',
          orderIndex: 1,
          title: 'Trophic Food Chains & Energy',
          description: 'Follow the flow of energy from the Sun to plants and animals.',
          icon: '☀️',
          skills: [
            {
              id: 'skill_living_vs_nonliving',
              unitId: 'unit_food_chains',
              courseId: 'science_ecosystems',
              subjectId: 'science',
              orderIndex: 1,
              title: 'Living vs Non-Living Things',
              description: 'Discover how living plants and animals grow, drink water, and reproduce.',
              icon: '🌱',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_k_living_things',
              practiceSetId: 'practice_living_vs_nonliving',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_plant_biology_g1',
              unitId: 'unit_food_chains',
              courseId: 'science_ecosystems',
              subjectId: 'science',
              orderIndex: 2,
              title: 'Plant Parts & Functions',
              description: 'Learn the role of roots, stems, leaves, and flowers in plant life.',
              icon: '🌸',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_living_vs_nonliving'],
              lessonId: 'lesson_g1_plant_parts',
              practiceSetId: 'practice_plant_biology_g1',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_producers_consumers',
              unitId: 'unit_food_chains',
              courseId: 'science_ecosystems',
              subjectId: 'science',
              orderIndex: 3,
              title: 'Producers & Consumers',
              description: 'Learn how plants make food from sunlight and herbivores graze.',
              icon: '🦌',
              ageBand: 'beginner',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_producers_consumers',
              practiceSetId: 'practice_producers_consumers',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_trophic_balance',
              unitId: 'unit_food_chains',
              courseId: 'science_ecosystems',
              subjectId: 'science',
              orderIndex: 4,
              title: 'Predator-Prey Equilibrium',
              description: 'Explore what happens when animal populations change.',
              icon: '🦊',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_producers_consumers'],
              lessonId: 'lesson_trophic_balance',
              practiceSetId: 'practice_trophic_balance',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_habitat_food_chains',
              unitId: 'unit_food_chains',
              courseId: 'science_ecosystems',
              subjectId: 'science',
              orderIndex: 5,
              title: 'Habitat Food Chains',
              description: 'Track energy flow from solar rays to plants, herbivores, and predators.',
              icon: '🌿',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_living_vs_nonliving'],
              lessonId: 'lesson_g2_habitat_food_chains',
              practiceSetId: 'practice_habitat_food_chains',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_ecosystem_balance',
              unitId: 'unit_food_chains',
              courseId: 'science_ecosystems',
              subjectId: 'science',
              orderIndex: 6,
              title: 'Food Webs & Ecosystem Equilibrium',
              description: 'Analyze complex multi-organism food webs and ecological balance.',
              icon: '🦉',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_habitat_food_chains'],
              lessonId: 'lesson_g5_ecosystem_balance',
              practiceSetId: 'practice_ecosystem_balance',
              capstoneGameId: 'ecosystem_sandbox',
            },
          ],
        },
      ],
    },
    {
      id: 'science_forces_motion',
      subjectId: 'science',
      title: 'Forces, Gravity & Motion',
      tagline: 'Pushes, pulls, tension, compression & kinetic energy',
      description: 'Understand how objects move, fall, bounce, and withstand physical structural stress.',
      icon: '⚙️',
      ageBand: 'developing',
      estimatedMinutes: 60,
      units: [
        {
          id: 'unit_simple_machines',
          courseId: 'science_forces_motion',
          subjectId: 'science',
          orderIndex: 1,
          title: 'Mechanics & Simple Machines',
          description: 'Levers, ramps, springs, and gears.',
          icon: '🎛️',
          skills: [
            {
              id: 'skill_gravity_inertia',
              unitId: 'unit_simple_machines',
              courseId: 'science_forces_motion',
              subjectId: 'science',
              orderIndex: 1,
              title: 'Gravity & Kinetic Energy',
              description: 'Predict how rolling balls gain speed down ramps.',
              icon: '🌐',
              ageBand: 'developing',
              prerequisiteSkillIds: [],
              lessonId: 'lesson_gravity_inertia',
              practiceSetId: 'practice_gravity_inertia',
              capstoneGameId: 'magic_machine',
            },
            {
              id: 'skill_truss_structures',
              unitId: 'unit_simple_machines',
              courseId: 'science_forces_motion',
              subjectId: 'science',
              orderIndex: 2,
              title: 'Tension & Compression in Bridges',
              description: 'Discover why triangles make the strongest structural shapes.',
              icon: '🏗️',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_gravity_inertia'],
              lessonId: 'lesson_truss_structures',
              practiceSetId: 'practice_truss_structures',
              capstoneGameId: 'invention_lab',
            },
            {
              id: 'skill_force_magnets',
              unitId: 'unit_simple_machines',
              courseId: 'science_forces_motion',
              subjectId: 'science',
              orderIndex: 3,
              title: 'Magnetic Forces & Polar Attraction',
              description: 'Investigate attraction and repulsion between North and South magnetic poles.',
              icon: '🧲',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_gravity_inertia'],
              lessonId: 'lesson_g3_force_magnets',
              practiceSetId: 'practice_force_magnets',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_energy_transfer',
              unitId: 'unit_simple_machines',
              courseId: 'science_forces_motion',
              subjectId: 'science',
              orderIndex: 4,
              title: 'Potential to Kinetic Energy Transfer',
              description: 'Examine how height and mass convert stored energy into kinetic motion.',
              icon: '⚡',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_force_magnets'],
              lessonId: 'lesson_g4_energy_transfer',
              practiceSetId: 'practice_energy_transfer',
              capstoneGameId: 'ecosystem_sandbox',
            },
            {
              id: 'skill_structural_engineering',
              unitId: 'unit_simple_machines',
              courseId: 'science_forces_motion',
              subjectId: 'science',
              orderIndex: 5,
              title: 'Structural Engineering: Tension & Compression',
              description: 'Design bridge trusses, cantilever beams, and compression arches.',
              icon: '🌉',
              ageBand: 'advanced',
              prerequisiteSkillIds: ['skill_energy_transfer'],
              lessonId: 'lesson_g6_structural_engineering',
              practiceSetId: 'practice_structural_engineering',
              capstoneGameId: 'creature_lab',
            },
          ],
        },
      ],
    },
    {
      id: 'science_astronomy',
      subjectId: 'science',
      title: 'Astronomy & The Solar System',
      tagline: 'Planets, stars, spectral classes & constellations',
      description: 'Journey through the cosmos, observe stellar colors, and map ancient constellations.',
      icon: '🌌',
      ageBand: 'developing',
      estimatedMinutes: 45,
      units: [
        {
          id: 'unit_stellar_astronomy',
          courseId: 'science_astronomy',
          subjectId: 'science',
          orderIndex: 1,
          title: 'Stars & Constellations',
          description: 'Classify stars by color/heat and map celestial coordinates.',
          icon: '✨',
          skills: [
            {
              id: 'skill_sun_our_star',
              unitId: 'unit_stellar_astronomy',
              courseId: 'science_astronomy',
              subjectId: 'science',
              orderIndex: 1,
              title: 'The Sun: Our Closest Star',
              description: 'Understand that our glowing Sun is a star providing light and warmth to Earth.',
              icon: '☀️',
              ageBand: 'beginner',
              prerequisiteSkillIds: ['skill_plant_biology_g1'],
              lessonId: 'lesson_sun_star',
              practiceSetId: 'practice_sun_star',
              capstoneGameId: 'cosmic_constellations',
            },
            {
              id: 'skill_star_spectral_colors',
              unitId: 'unit_stellar_astronomy',
              courseId: 'science_astronomy',
              subjectId: 'science',
              orderIndex: 2,
              title: 'Star Temperatures & Colors',
              description: 'Learn why blue stars are hot and red stars are cool.',
              icon: '⭐',
              ageBand: 'developing',
              prerequisiteSkillIds: ['skill_sun_our_star'],
              lessonId: 'lesson_spectral_colors',
              practiceSetId: 'practice_spectral_colors',
              capstoneGameId: 'cosmic_constellations',
            },
            {
              id: 'skill_solar_spectral_classes',
              unitId: 'unit_stellar_astronomy',
              courseId: 'science_astronomy',
              subjectId: 'science',
              orderIndex: 3,
              title: 'Stellar Spectra & Solar Classes',
              description: 'Classify stars across O/B blue giants, G yellow stars, and M red dwarfs.',
              icon: '🔭',
              ageBand: 'intermediate',
              prerequisiteSkillIds: ['skill_sun_our_star'],
              lessonId: 'lesson_g5_solar_spectral_classes',
              practiceSetId: 'practice_solar_spectral_classes',
              capstoneGameId: 'cosmic_constellations',
            },
          ],
        },
      ],
    },
  ],
}
