import type { StandaloneGameMetadata } from '../../types/games/gameUniverse'
import type { CognitiveDomain } from '../../types/experience'

export const ORBIS_GAMES: StandaloneGameMetadata[] = [
  {
    id: 'creature_lab',
    title: 'Creature Lab',
    subtitle: 'Alchemical Discovery Laboratory',
    category: 'discovery',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic', 'vocabulary'],
    icon: '🧪',
    route: '/games/creature-lab',
    ageMin: 4,
    ageMax: 10,
    status: 'playable',
    heroBannerColor: 'linear-gradient(135deg, #1e1b4b 0%, #4338ca 50%, #ec4899 100%)',
    accentGlow: 'rgba(236, 72, 153, 0.5)',
    description: 'Mix magical starlight essences in an enchanted bubbling cauldron to discover, nurture, and collect living mythical companions.',
    features: ['5 Prime Essences', '8 Unique Species', 'Harmonic Fluid Reactions', 'Almanac Collection'],
  },
  {
    id: 'world_builder',
    title: 'World Builder',
    subtitle: 'Spatial Physics & Bridge Engineering',
    category: 'spatial_physics',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '🏗️',
    route: '/games/world-builder',
    ageMin: 5,
    ageMax: 12,
    status: 'in_development',
    heroBannerColor: 'linear-gradient(135deg, #064e3b 0%, #059669 50%, #3b82f6 100%)',
    accentGlow: 'rgba(16, 185, 129, 0.5)',
    description: 'Construct load-bearing bridges, bouncy ramps, and sky pathways to guide wandering Orblings across yawning chasms.',
    features: ['2D Physics Engine', 'Orbling Sprites', 'Material Unlocks', 'Sandbox Mode'],
  },
  {
    id: 'brainstorm_arena',
    title: 'Brainstorm Arena',
    subtitle: 'Rapid Cognitive Speed Arcade',
    category: 'arcade_speed',
    primaryDomain: 'memory',
    secondaryDomains: ['logic', 'comprehension'],
    icon: '⚡',
    route: '/games/brainstorm-arena',
    ageMin: 6,
    ageMax: 12,
    status: 'in_development',
    heroBannerColor: 'linear-gradient(135deg, #78350f 0%, #d97706 50%, #f59e0b 100%)',
    accentGlow: 'rgba(245, 158, 11, 0.5)',
    description: 'Test your working memory, reaction time, and executive flexibility in high-energy 60-second micro-challenge matches.',
    features: ['60s Match Medley', 'Combo Multipliers', 'Daily Arena Cup', 'Crown Rewards'],
  },
  {
    id: 'mystery_detective',
    title: 'Mystery Detective',
    subtitle: 'Deductive Logic & Grid Investigation',
    category: 'logic_deduction',
    primaryDomain: 'logic',
    secondaryDomains: ['comprehension', 'vocabulary'],
    icon: '🔍',
    route: '/games/mystery-detective',
    ageMin: 6,
    ageMax: 12,
    status: 'in_development',
    heroBannerColor: 'linear-gradient(135deg, #311042 0%, #701a75 50%, #c026d3 100%)',
    accentGlow: 'rgba(192, 38, 211, 0.5)',
    description: 'Interrogate suspects, connect clues on the detective pin-board, and use constraint logic grids to solve whimsical city mysteries.',
    features: ['Constraint Grids', 'Suspect Board', 'Detective Ranks', 'Evidence Synthesis'],
  },
  {
    id: 'dragon_rescue',
    title: 'Dragon Rescue',
    subtitle: 'Algorithmic Routing & Visual Coding',
    category: 'coding_algorithm',
    primaryDomain: 'logic',
    secondaryDomains: ['memory'],
    icon: '🐉',
    route: '/games/dragon-rescue',
    ageMin: 5,
    ageMax: 11,
    status: 'in_development',
    heroBannerColor: 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 50%, #60a5fa 100%)',
    accentGlow: 'rgba(37, 99, 235, 0.5)',
    description: 'Program action command tiles to guide baby dragons through floating mazes, collecting star crystals along the way.',
    features: ['Visual Code Tiles', 'Loops & Conditions', '3-Star Efficiency', 'Baby Dragon Sanctuary'],
  },
  {
    id: 'beat_forge',
    title: 'Beat Forge',
    subtitle: 'Rhythm & Phonemic Pattern Forge',
    category: 'rhythm_music',
    primaryDomain: 'phonics',
    secondaryDomains: ['memory', 'creativity'],
    icon: '🎵',
    route: '/games/beat-forge',
    ageMin: 4,
    ageMax: 10,
    status: 'coming_soon',
    heroBannerColor: 'linear-gradient(135deg, #831843 0%, #db2777 50%, #f472b6 100%)',
    accentGlow: 'rgba(219, 39, 119, 0.5)',
    description: 'Forge musical spells in rhythm with cosmic beats, matching syllable patterns to unlock ancient melody crystals.',
    features: ['Web Audio Synthesizer', 'Syllable Beats', 'Loop Sequencer', 'Melody Crystals'],
  },
  {
    id: 'rune_machine',
    title: 'Rune Machine',
    subtitle: 'Root Words & Etymology Forge',
    category: 'etymology_words',
    primaryDomain: 'vocabulary',
    secondaryDomains: ['comprehension'],
    icon: '🔠',
    route: '/games/rune-machine',
    ageMin: 7,
    ageMax: 12,
    status: 'coming_soon',
    heroBannerColor: 'linear-gradient(135deg, #451a03 0%, #b45309 50%, #fde047 100%)',
    accentGlow: 'rgba(180, 83, 9, 0.5)',
    description: 'Slot prefix gears, root stones, and suffix springs into a steam-powered printing press to forge powerful enchanted words.',
    features: ['Prefix/Root/Suffix Gears', 'Latin & Greek Roots', 'Steam Mechanics', 'Enchanted Lexicon'],
  },
  {
    id: 'shadow_hunt',
    title: 'Shadow Hunt',
    subtitle: 'Parallax Visual Search & Ecology',
    category: 'discovery',
    primaryDomain: 'memory',
    secondaryDomains: ['creativity'],
    icon: '🌌',
    route: '/games/shadow-hunt',
    ageMin: 3,
    ageMax: 8,
    status: 'coming_soon',
    heroBannerColor: 'linear-gradient(135deg, #022c22 0%, #065f46 50%, #34d399 100%)',
    accentGlow: 'rgba(5, 150, 105, 0.5)',
    description: 'Explore 2.5D layered biomes with a starlight lantern to discover hidden camouflaged creatures in serene nighttime environments.',
    features: ['Parallax Biomes', 'Lantern Light Cone', 'Field Journal Stamps', 'Calm Bedtime Mode'],
  },
  {
    id: 'tiny_world',
    title: 'Tiny World',
    subtitle: 'Ecosystem Balance & Biosphere Sandbox',
    category: 'systems_ecology',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '🌿',
    route: '/games/tiny-world',
    ageMin: 7,
    ageMax: 12,
    status: 'coming_soon',
    heroBannerColor: 'linear-gradient(135deg, #14532d 0%, #16a34a 50%, #86efac 100%)',
    accentGlow: 'rgba(22, 163, 74, 0.5)',
    description: 'Cultivate and balance an enchanted micro-biosphere with flora, pollinators, weather systems, and biological equilibrium.',
    features: ['Terrarium Simulation', 'Food Web Dynamics', 'Weather Controls', 'Species Evolution'],
  },
  {
    id: 'dream_studio',
    title: 'Dream Studio',
    subtitle: 'Narrative Theatre & Character Craft',
    category: 'narrative_craft',
    primaryDomain: 'creativity',
    secondaryDomains: ['comprehension', 'vocabulary'],
    icon: '🎨',
    route: '/games/dream-studio',
    ageMin: 4,
    ageMax: 12,
    status: 'coming_soon',
    heroBannerColor: 'linear-gradient(135deg, #581c87 0%, #9333ea 50%, #c084fc 100%)',
    accentGlow: 'rgba(147, 51, 234, 0.5)',
    description: 'Craft original animated puppet characters and stage interactive narrative plays that can export into personalized bedtime stories.',
    features: ['Puppet Rigging', 'Stage Plays', 'Voice Recording', 'AI Story Export'],
  },
]

export const gameRegistry = {
  getAllGames(): StandaloneGameMetadata[] {
    return [...ORBIS_GAMES]
  },

  getPlayableGames(): StandaloneGameMetadata[] {
    return ORBIS_GAMES.filter((g) => g.status === 'playable')
  },

  getInDevelopmentGames(): StandaloneGameMetadata[] {
    return ORBIS_GAMES.filter((g) => g.status === 'in_development')
  },

  getComingSoonGames(): StandaloneGameMetadata[] {
    return ORBIS_GAMES.filter((g) => g.status === 'coming_soon')
  },

  getGameById(id: string): StandaloneGameMetadata | undefined {
    return ORBIS_GAMES.find((g) => g.id === id)
  },

  getGamesByDomain(domain: CognitiveDomain): StandaloneGameMetadata[] {
    return ORBIS_GAMES.filter(
      (g) => g.primaryDomain === domain || g.secondaryDomains.includes(domain)
    )
  },
}
