import type { PlaygroundGameId, PlaygroundGameMetadata } from '../../types/playground'
import type { CognitiveDomain } from '../../types/experience'

/**
 * 🪐 THE 10 CANONICAL ORBIS FLAGSHIP GAMES
 * Exactly 10 flagship interactive stations, with distinct mechanics, rich visual identities, and 100% playable routes.
 */
export const PLAYGROUND_REGISTRY: Record<PlaygroundGameId, PlaygroundGameMetadata> = {
  potion_scales: {
    id: 'potion_scales',
    title: 'Potion Market Scales',
    subtitle: 'Physical Balance, Fractions & Liquid Alchemy',
    category: 'alchemy_discovery',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity', 'vocabulary'],
    icon: '⚖️',
    route: '/playroom/potion-scales',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #064e3b 0%, #0d9488 50%, #06b6d4 100%)',
    accentGlow: 'rgba(13, 148, 136, 0.5)',
    description: 'Experiment with brass weights, missing pouches, fractions, and liquid beakers on a magical physical balance scale to brew miraculous customer potions.',
    learningObjectives: ['Conservation of Mass', 'Algebraic Equivalence', 'Fractional Parts & Decimals', 'Liquid Volume & Density'],
    keyMechanics: ['Physical Fulcrum Balance Tilt', 'Tactile Weight Drag & Drop', 'Liquid Beaker Pouring', 'Science of Wonder Cards'],
    estimatedSessionSeconds: 60,
    rankOrder: 1,
  },
  rhythm_spells: {
    id: 'rhythm_spells',
    title: 'Rhythm Spells',
    subtitle: 'Auditory Patterning & Musical Phonics',
    category: 'musical_patterns',
    primaryDomain: 'phonics',
    secondaryDomains: ['memory'],
    icon: '🎵',
    route: '/playroom/rhythm-spells',
    ageRange: { min: 4, max: 10 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #134e4a 0%, #0d9488 50%, #2dd4bf 100%)',
    accentGlow: 'rgba(13, 148, 136, 0.5)',
    description: 'Echo musical rhythms and complete syllable beat patterns on pentatonic rune drums to cast dazzling harmonic sound spells.',
    learningObjectives: ['Syllabic Rhythm Phonics', 'Auditory Patterning', 'Mathematical Fractions', 'Beat Synchronization'],
    keyMechanics: ['Rune Drum Tap', 'Pentatonic Micro-Scheduling', 'Visual Ripple Harmonics'],
    estimatedSessionSeconds: 45,
    rankOrder: 2,
  },
  word_trace: {
    id: 'word_trace',
    title: 'Word Trace Quest',
    subtitle: 'Vocabulary Quest & Orthographic Clues',
    category: 'linguistic_craft',
    primaryDomain: 'vocabulary',
    secondaryDomains: ['phonics', 'comprehension'],
    icon: '🔤',
    route: '/stories',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #581c87 0%, #7e22ce 50%, #a855f7 100%)',
    accentGlow: 'rgba(168, 85, 247, 0.5)',
    description: 'Uncover hidden vocabulary clues, decipher phonics roots, and spell target story words with 4-tier progressive hint assistance.',
    learningObjectives: ['Vocabulary Acquisition', 'Orthographic Spelling', 'Phonemic Awareness', 'Contextual Reading'],
    keyMechanics: ['Interactive Tile Scrambler', '4-Tier Progressive Hints', 'Cloze Context Evaluation'],
    estimatedSessionSeconds: 60,
    rankOrder: 3,
  },
  magic_machine: {
    id: 'magic_machine',
    title: 'Magic Machine Lab',
    subtitle: 'Physics Contraptions & Kinetic Sandbox',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '⚙️',
    route: '/playroom/magic-machine',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 50%, #06b6d4 100%)',
    accentGlow: 'rgba(37, 99, 235, 0.5)',
    description: 'Combine springs, magnets, blowers, ramps, and bumpers to construct ingenious Rube Goldberg machines that guide little Sproutlings safely to the Star Cradle.',
    learningObjectives: ['Mechanical Intuition', 'Physics Problem Solving', 'Iterative Experimentation', 'Cause & Effect'],
    keyMechanics: ['Tactile Component Placement', 'Real-Time 2D Physics Simulation', 'Gentle Safe-Failure Loop', 'Deterministic Solutions'],
    estimatedSessionSeconds: 90,
    rankOrder: 4,
  },
  invention_lab: {
    id: 'invention_lab',
    title: 'Invention Lab',
    subtitle: 'Structural Engineering & Blueprint Workshop',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '🏗️',
    route: '/playroom/invention-lab',
    ageRange: { min: 5, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #0c4a6e 0%, #0284c7 50%, #38bdf8 100%)',
    accentGlow: 'rgba(56, 189, 248, 0.5)',
    description: 'Design load-bearing bridges, truss scaffolds, and suspension cables to guide the heavy Starling Rover across canyon chasms.',
    learningObjectives: ['Structural Mechanics', 'Tension vs Compression Forces', 'Iterative Prototyping', 'Resource Budget Optimization'],
    keyMechanics: ['Blueprint Grid Snapping', 'Truss Stress Testing', 'Load Limit Physics', 'Real-Time Failure Diagnostics'],
    estimatedSessionSeconds: 90,
    rankOrder: 5,
  },
  spellforge: {
    id: 'spellforge',
    title: 'Spellforge Anvil',
    subtitle: 'Runic Word Crafting & Morpheme Blacksmithing',
    category: 'linguistic_craft',
    primaryDomain: 'vocabulary',
    secondaryDomains: ['phonics', 'creativity'],
    icon: '🔥',
    route: '/playroom/spellforge',
    ageRange: { min: 4, max: 10 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #7c2d12 0%, #ea580c 50%, #fbbf24 100%)',
    accentGlow: 'rgba(234, 88, 12, 0.5)',
    description: 'Assemble glowing phonetic runes and root morphemes on an enchanted anvil to forge living animated spells and creatures.',
    learningObjectives: ['Phonemic Awareness', 'Morpheme Assembly (Prefix/Suffix)', 'Spelling Fluency', 'Word Families'],
    keyMechanics: ['Rune Drag & Snap', 'Hammer Strike Activation', 'Living Spell Transformation'],
    estimatedSessionSeconds: 60,
    rankOrder: 6,
  },
  ecosystem_sandbox: {
    id: 'ecosystem_sandbox',
    title: 'Ecosystem Sandbox',
    subtitle: 'Living Ecological Sandbox Sanctuary',
    category: 'ecological_systems',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic'],
    icon: '🏝️',
    route: '/playroom/ecosystem-sandbox',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #064e3b 0%, #059669 50%, #10b981 100%)',
    accentGlow: 'rgba(16, 185, 129, 0.5)',
    description: 'Place terrain tiles, rivers, and flora on your floating island sanctuary, observing ecological chain reactions that attract living wildlife.',
    learningObjectives: ['Systems Ecology', 'Spatial Planning', 'Environmental Cause-and-Effect', 'Creative Expression'],
    keyMechanics: ['Isometric Tile Snapping', 'Cellular Automata Synergy', 'Creature Habitat Balancing'],
    estimatedSessionSeconds: 180,
    rankOrder: 7,
  },
  mystery_detective: {
    id: 'mystery_detective',
    title: 'Mystery Detective',
    subtitle: 'Forensic Investigation & Whodunit Deduction',
    category: 'deductive_logic',
    primaryDomain: 'logic',
    secondaryDomains: ['comprehension', 'vocabulary'],
    icon: '🔍',
    route: '/playroom/mystery-detective',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)',
    accentGlow: 'rgba(67, 56, 202, 0.5)',
    description: 'Inspect crime scene hotspots with forensic tools, gather evidence on your pinboard, eliminate suspects, and deduce playful culprits with Science of Wonder insights.',
    learningObjectives: ['Constraint Satisfaction Reasoning', 'Forensic Evidence Evaluation', 'Scientific Concepts (Optics, Olfaction, Mechanics)', 'Elimination Logic'],
    keyMechanics: ['Forensic Tool Belt (Magnifying Glass, UV Brush, Listening Horn, Decoder Lens)', 'Evidence Pinboard', 'Suspect Lineup & Elimination Cross-Off', 'Science of Wonder Cards'],
    estimatedSessionSeconds: 60,
    rankOrder: 8,
  },
  robopath: {
    id: 'robopath',
    title: 'Robo-Path Academy',
    subtitle: 'Algorithmic Programming & Grid Robotics',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '🤖',
    route: '/playroom/robopath',
    ageRange: { min: 5, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #0284c7 0%, #0369a1 50%, #075985 100%)',
    accentGlow: 'rgba(2, 132, 199, 0.5)',
    description: 'Program BEEP-0 using directional tokens, loops, and jump routines across futuristic grid terrain to collect power crystals.',
    learningObjectives: ['Algorithmic Thinking', 'Sequencing & Loops', 'Debugging & Spatial Navigation', 'Computational Logic'],
    keyMechanics: ['AST Command Token Builder', 'Animated Step Interpreter', 'Obstacle Avoidance Logic'],
    estimatedSessionSeconds: 90,
    rankOrder: 9,
  },
  cosmic_constellations: {
    id: 'cosmic_constellations',
    title: 'Cosmic Constellations',
    subtitle: 'Astronomical Star Charting & Geometry',
    category: 'alchemy_discovery',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic'],
    icon: '✨',
    route: '/playroom/constellations',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #312e81 0%, #4338ca 50%, #6366f1 100%)',
    accentGlow: 'rgba(99, 102, 241, 0.5)',
    description: 'Chart stellar nebulae, classify spectral star classes, and draw celestial constellations in deep space observatories.',
    learningObjectives: ['Astronomical Science', 'Geometric Pattern Recognition', 'Spatial Coordinate Reasoning', 'Stellar Evolution'],
    keyMechanics: ['Interactive Star Linking', 'Spectral Class Glows', 'Constellation Awakening'],
    estimatedSessionSeconds: 60,
    rankOrder: 10,
  },

  // Aliases for seamless backward compatibility
  world_builder: {
    id: 'world_builder',
    title: 'Ecosystem Sandbox',
    subtitle: 'Living Ecological Sandbox Sanctuary',
    category: 'ecological_systems',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic'],
    icon: '🏝️',
    route: '/playroom/ecosystem-sandbox',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #064e3b 0%, #059669 50%, #10b981 100%)',
    accentGlow: 'rgba(16, 185, 129, 0.5)',
    description: 'Living Ecological Sandbox Sanctuary.',
    learningObjectives: ['Systems Ecology', 'Biodiversity Equilibrium', 'Environmental Simulation'],
    keyMechanics: ['Isometric Tile Snapping'],
    estimatedSessionSeconds: 180,
    rankOrder: 7,
  },
  word_detective: {
    id: 'word_detective',
    title: 'Word Trace Quest',
    subtitle: 'Vocabulary Quest & Orthographic Clues',
    category: 'linguistic_craft',
    primaryDomain: 'vocabulary',
    secondaryDomains: ['phonics'],
    icon: '🔤',
    route: '/stories',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #581c87 0%, #7e22ce 50%, #a855f7 100%)',
    accentGlow: 'rgba(168, 85, 247, 0.5)',
    description: 'Vocabulary Quest & Orthographic Clues.',
    learningObjectives: ['Vocabulary Acquisition', 'Orthographic Recognition', 'Contextual Reading'],
    keyMechanics: ['Interactive Tile Scrambler'],
    estimatedSessionSeconds: 60,
    rankOrder: 3,
  },
  memory_museum: {
    id: 'memory_museum',
    title: 'Memory Museum',
    subtitle: 'Shifting Curiosity Gallery & Working Memory',
    category: 'executive_memory',
    primaryDomain: 'memory',
    secondaryDomains: ['logic'],
    icon: '🏛️',
    route: '/playroom/memory-museum',
    ageRange: { min: 4, max: 11 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 50%, #ec4899 100%)',
    accentGlow: 'rgba(124, 58, 237, 0.5)',
    description: 'Explore atmospheric museum galleries and uncover matching ancient relics using 3D perspective flip physics and spatial recall.',
    learningObjectives: ['Working Memory Updating', 'Spatial Recall', 'Pattern Retention'],
    keyMechanics: ['3D Card Perspective Flip'],
    estimatedSessionSeconds: 45,
    rankOrder: 11,
  },
  creature_lab: {
    id: 'creature_lab',
    title: 'Creature Lab',
    subtitle: 'Starlight Alchemy & Scientific Wonder',
    category: 'alchemy_discovery',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic'],
    icon: '🧪',
    route: '/games/creature-lab',
    ageRange: { min: 4, max: 10 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e1b4b 0%, #4338ca 50%, #ec4899 100%)',
    accentGlow: 'rgba(236, 72, 153, 0.5)',
    description: 'Mix magical starlight essences in an enchanted cauldron to discover 24 mythical species.',
    learningObjectives: ['Hypothesis Testing', 'Chemical Combinatorics', 'Species Taxonomy'],
    keyMechanics: ['Essence Drag & Drop'],
    estimatedSessionSeconds: 60,
    rankOrder: 12,
  },
  creature_care: {
    id: 'creature_care',
    title: 'Creature Care Lab',
    subtitle: 'Ethology, Empathy & Habitat Nurturing',
    category: 'empathy_simulation',
    primaryDomain: 'comprehension',
    secondaryDomains: ['creativity'],
    icon: '🐾',
    route: '/sanctuary',
    ageRange: { min: 3, max: 9 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #831843 0%, #db2777 50%, #f472b6 100%)',
    accentGlow: 'rgba(219, 39, 119, 0.5)',
    description: 'Diagnose non-verbal cues from hatched companions and care for your sanctuary.',
    learningObjectives: ['Social-Emotional Intelligence', 'Empathy Simulation', 'Biological Nurturing'],
    keyMechanics: ['Tactile Grooming & Feeding'],
    estimatedSessionSeconds: 60,
    rankOrder: 13,
  },
  skyship_builder: {
    id: 'skyship_builder',
    title: 'Skyship Builder',
    subtitle: 'Aerial Trajectory & Path Planning',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '⛵',
    route: '/playroom/invention-lab',
    ageRange: { min: 5, max: 11 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #0c4a6e 0%, #0284c7 50%, #38bdf8 100%)',
    accentGlow: 'rgba(2, 132, 199, 0.5)',
    description: 'Build aerial routes through floating archipelago islands.',
    learningObjectives: ['Spatial Route Planning', 'Vector Physics', 'Structural Navigation'],
    keyMechanics: ['Track Tile Grid'],
    estimatedSessionSeconds: 75,
    rankOrder: 14,
  },
  time_machine: {
    id: 'time_machine',
    title: 'Time Machine',
    subtitle: 'Causal Sequencing & Chronological Riddles',
    category: 'temporal_reasoning',
    primaryDomain: 'comprehension',
    secondaryDomains: ['logic'],
    icon: '⏳',
    route: '/playroom/memory-museum',
    ageRange: { min: 5, max: 11 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #713f12 0%, #b45309 50%, #fbbf24 100%)',
    accentGlow: 'rgba(180, 83, 9, 0.5)',
    description: 'Causal Sequencing & Chronological Riddles.',
    learningObjectives: ['Narrative Chronology', 'Causal Sequencing', 'Temporal Deduction'],
    keyMechanics: ['Timeline Card Assembly'],
    estimatedSessionSeconds: 60,
    rankOrder: 15,
  },
  orbis_quest_run: {
    id: 'orbis_quest_run',
    title: 'ORBis Quest Run',
    subtitle: 'Side-Scrolling Platformer & Micro-Challenges',
    category: 'adventure_action',
    primaryDomain: 'comprehension',
    secondaryDomains: ['memory'],
    icon: '🏃',
    route: '/playroom/magic-machine',
    ageRange: { min: 5, max: 11 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #881337 0%, #e11d48 50%, #fda4af 100%)',
    accentGlow: 'rgba(225, 29, 72, 0.5)',
    description: 'Side-Scrolling Platformer & Micro-Challenges.',
    learningObjectives: ['Rapid Pattern Classification'],
    keyMechanics: ['Auto-Run Momentum'],
    estimatedSessionSeconds: 90,
    rankOrder: 16,
  },
}

export const CANONICAL_FLAGSHIP_IDS: PlaygroundGameId[] = [
  'potion_scales',
  'rhythm_spells',
  'word_trace',
  'magic_machine',
  'invention_lab',
  'spellforge',
  'ecosystem_sandbox',
  'mystery_detective',
  'robopath',
  'cosmic_constellations',
]

/**
 * Returns the exact 10 Canonical Flagship Games in rank order.
 */
export function getCanonicalFlagshipGames(): PlaygroundGameMetadata[] {
  return CANONICAL_FLAGSHIP_IDS.map((id) => PLAYGROUND_REGISTRY[id]).filter(Boolean)
}

export function getAllPlaygroundGames(): PlaygroundGameMetadata[] {
  return getCanonicalFlagshipGames()
}

export function getPlaygroundGame(id: string): PlaygroundGameMetadata | undefined {
  return PLAYGROUND_REGISTRY[id as PlaygroundGameId]
}

export function getPlayablePlaygroundGames(): PlaygroundGameMetadata[] {
  return getCanonicalFlagshipGames()
}

export function getPlaygroundGamesByDomain(domain: CognitiveDomain): PlaygroundGameMetadata[] {
  return getCanonicalFlagshipGames().filter(
    (game) => game.primaryDomain === domain || game.secondaryDomains.includes(domain)
  )
}
