import type { PlaygroundGameId, PlaygroundGameMetadata } from '../../types/playground'
import type { CognitiveDomain } from '../../types/experience'

export const PLAYGROUND_REGISTRY: Record<PlaygroundGameId, PlaygroundGameMetadata> = {
  spellforge: {
    id: 'spellforge',
    title: 'Spellforge',
    subtitle: 'Runic Word Crafting & Morpheme Anvil',
    category: 'linguistic_craft',
    primaryDomain: 'vocabulary',
    secondaryDomains: ['phonics', 'creativity'],
    icon: '🔥',
    route: '/playground/spellforge',
    ageRange: { min: 4, max: 10 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #7c2d12 0%, #ea580c 50%, #fbbf24 100%)',
    accentGlow: 'rgba(234, 88, 12, 0.5)',
    description: 'Assemble glowing phonetic runes and root morphemes on an enchanted anvil to awaken living animated spells and creatures.',
    learningObjectives: ['Phonemic Awareness', 'Morpheme Assembly (Prefix/Suffix)', 'Spelling Fluency', 'Word Families'],
    keyMechanics: ['Rune Drag & Snap', 'Hammer Strike Activation', 'Living Spell Transformation'],
    estimatedSessionSeconds: 60,
    rankOrder: 1,
  },
  magic_machine: {
    id: 'magic_machine',
    title: 'Magic Machine Lab',
    subtitle: 'Physics Contraptions & Engineering Sandbox',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '⚙️',
    route: '/playroom/magic-machine',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 50%, #06b6d4 100%)',
    accentGlow: 'rgba(37, 99, 235, 0.5)',
    description: 'Combine springs, magnets, blowers, ramps, and bumpers to construct ingenious Rube Goldberg machines that guide little Sproutlings safely to the Star Cradle.',
    learningObjectives: ['Mechanical Intuition', 'Physics Problem Solving', 'Iterative Experimentation', 'Cause & Effect'],
    keyMechanics: ['Tactile Component Placement', 'Real-Time 2D Physics Simulation', 'Gentle Safe-Failure Loop', 'Deterministic Solutions'],
    estimatedSessionSeconds: 90,
    rankOrder: 2,
  },
  invention_lab: {
    id: 'invention_lab',
    title: 'Invention Lab',
    subtitle: 'Physics Contraptions & Engineering Puzzles',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '⚙️',
    route: '/playroom/magic-machine',
    ageRange: { min: 5, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 50%, #06b6d4 100%)',
    accentGlow: 'rgba(37, 99, 235, 0.5)',
    description: 'Combine springs, magnets, blowers, and ramps to construct ingenious Rube Goldberg contraptions that guide little Sproutlings safely.',
    learningObjectives: ['Mechanical Intuition', 'Physics Problem Solving', 'Iterative Experimentation', 'Cause & Effect'],
    keyMechanics: ['Toolbox Placement', 'Real-Time Physics Simulation', 'Gentle Iteration Loop'],
    estimatedSessionSeconds: 90,
    rankOrder: 2,
  },
  memory_museum: {
    id: 'memory_museum',
    title: 'Memory Museum',
    subtitle: 'Shifting Curiosity Gallery & Working Memory',
    category: 'executive_memory',
    primaryDomain: 'memory',
    secondaryDomains: ['logic', 'comprehension'],
    icon: '🏛️',
    route: '/playground/memory-museum',
    ageRange: { min: 4, max: 11 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 50%, #ec4899 100%)',
    accentGlow: 'rgba(124, 58, 237, 0.5)',
    description: 'Observe dynamic artifact pedestals in a magical curiosity museum and deduce what vanished, shifted, or transformed when the lights flicker.',
    learningObjectives: ['Working Memory Updating', 'Visual Spatial Attention', 'Inhibitory Focus', 'Pattern Recall'],
    keyMechanics: ['Observation Phase (3-5s)', 'Curtain Drop Shift', 'Deductive Artifact Tagging'],
    estimatedSessionSeconds: 45,
    rankOrder: 3,
  },
  creature_lab: {
    id: 'creature_lab',
    title: 'Creature Lab',
    subtitle: 'Starlight Alchemy & Scientific Wonder',
    category: 'alchemy_discovery',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic', 'vocabulary'],
    icon: '🧪',
    route: '/games/creature-lab',
    ageRange: { min: 4, max: 10 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e1b4b 0%, #4338ca 50%, #ec4899 100%)',
    accentGlow: 'rgba(236, 72, 153, 0.5)',
    description: 'Mix magical starlight essences in an enchanted bubbling cauldron to discover 24 mythical species, learn scientific concepts, and expand your Almanac.',
    learningObjectives: ['Hypothesis Testing', 'Scientific Method', 'Real-World Science Concepts', 'Categorization'],
    keyMechanics: ['Essence Drag & Drop', 'Fluid Reaction Blending', 'Prediction & Hatching', 'Almanac Tracking'],
    estimatedSessionSeconds: 60,
    rankOrder: 4,
  },
  world_builder: {
    id: 'world_builder',
    title: 'World Builder',
    subtitle: 'Living Ecological Sandbox Sanctuary',
    category: 'ecological_systems',
    primaryDomain: 'creativity',
    secondaryDomains: ['logic'],
    icon: '🏝️',
    route: '/playground/world-builder',
    ageRange: { min: 4, max: 12 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #064e3b 0%, #059669 50%, #10b981 100%)',
    accentGlow: 'rgba(16, 185, 129, 0.5)',
    description: 'Place terrain tiles, rivers, and flora on your floating island sanctuary, observing ecological chain reactions that attract living wildlife.',
    learningObjectives: ['Systems Ecology', 'Spatial Planning', 'Environmental Cause-and-Effect', 'Creative Expression'],
    keyMechanics: ['Isometric Tile Snapping', 'Cellular Automata Synergy', 'Creature Habitat Balancing'],
    estimatedSessionSeconds: 180,
    rankOrder: 5,
  },
  mystery_detective: {
    id: 'mystery_detective',
    title: 'Mystery Detective',
    subtitle: 'Forensic Investigation & Whodunit Deduction',
    category: 'deductive_logic',
    primaryDomain: 'logic',
    secondaryDomains: ['comprehension', 'vocabulary'],
    icon: '🔍',
    route: '/playroom/mystery-detective',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)',
    accentGlow: 'rgba(67, 56, 202, 0.5)',
    description: 'Inspect crime scene hotspots with forensic tools, gather evidence on your pinboard, eliminate suspects, and deduce playful culprits with Science of Wonder insights.',
    learningObjectives: ['Constraint Satisfaction Reasoning', 'Forensic Evidence Evaluation', 'Scientific Concepts (Optics, Olfaction, Mechanics)', 'Elimination Logic'],
    keyMechanics: ['Forensic Tool Belt (Magnifying Glass, UV Brush, Listening Horn, Decoder Lens)', 'Evidence Pinboard', 'Suspect Lineup & Elimination Cross-Off', 'Science of Wonder Cards'],
    estimatedSessionSeconds: 60,
    rankOrder: 3,
  },
  potion_scales: {
    id: 'potion_scales',
    title: 'Potion Market Scales',
    subtitle: 'Physical Balance, Fractions & Liquid Alchemy',
    category: 'alchemy_discovery',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity', 'vocabulary'],
    icon: '⚖️',
    route: '/playroom/potion-scales',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #064e3b 0%, #0d9488 50%, #06b6d4 100%)',
    accentGlow: 'rgba(13, 148, 136, 0.5)',
    description: 'Experiment with crystal weights, missing pouches, fractions, and liquid beakers on a magical physical balance scale to brew miraculous customer potions.',
    learningObjectives: ['Conservation of Mass', 'Algebraic Equivalence', 'Fractional Parts & Decimals', 'Liquid Volume & Density'],
    keyMechanics: ['Physical Fulcrum Balance Tilt', 'Tactile Weight Drag & Drop', 'Liquid Beaker Pouring', 'Science of Wonder Cards'],
    estimatedSessionSeconds: 60,
    rankOrder: 4,
  },
  word_detective: {
    id: 'word_detective',
    title: 'Mystery Detective',
    subtitle: 'Forensic Investigation & Whodunit Deduction',
    category: 'deductive_logic',
    primaryDomain: 'logic',
    secondaryDomains: ['comprehension', 'vocabulary'],
    icon: '🔍',
    route: '/playroom/mystery-detective',
    ageRange: { min: 4, max: 12 },
    status: 'playable',
    isPlayable: true,
    heroBannerColor: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)',
    accentGlow: 'rgba(67, 56, 202, 0.5)',
    description: 'Inspect crime scene hotspots with forensic tools, gather evidence on your pinboard, eliminate suspects, and deduce playful culprits.',
    learningObjectives: ['Constraint Satisfaction Reasoning', 'Forensic Evidence Evaluation', 'Scientific Concepts', 'Elimination Logic'],
    keyMechanics: ['Forensic Tool Belt', 'Evidence Pinboard', 'Suspect Lineup & Elimination', 'Science of Wonder Cards'],
    estimatedSessionSeconds: 60,
    rankOrder: 6,
  },
  creature_care: {
    id: 'creature_care',
    title: 'Creature Care Lab',
    subtitle: 'Ethology, Empathy & Habitat Nurturing',
    category: 'empathy_simulation',
    primaryDomain: 'comprehension',
    secondaryDomains: ['creativity'],
    icon: '🐾',
    route: '/playground/creature-care',
    ageRange: { min: 3, max: 9 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #831843 0%, #db2777 50%, #f472b6 100%)',
    accentGlow: 'rgba(219, 39, 119, 0.5)',
    description: 'Diagnose non-verbal cues from hatched companions, crafting personalized diets, sensory blankets, and music to earn Trust Hearts.',
    learningObjectives: ['Social-Emotional Intelligence', 'Animal Behavior Basics', 'Empathy & Caretaking', 'Biological Needs'],
    keyMechanics: ['Mood Diagnosis', 'Tactile Grooming & Feeding', 'Trust Heart Bonding'],
    estimatedSessionSeconds: 60,
    rankOrder: 7,
  },
  skyship_builder: {
    id: 'skyship_builder',
    title: 'Skyship Builder',
    subtitle: 'Aerial Trajectory & Path Planning',
    category: 'physics_engineering',
    primaryDomain: 'logic',
    secondaryDomains: ['creativity'],
    icon: '⛵',
    route: '/playground/skyship-builder',
    ageRange: { min: 5, max: 11 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #0c4a6e 0%, #0284c7 50%, #38bdf8 100%)',
    accentGlow: 'rgba(2, 132, 199, 0.5)',
    description: 'Build aerial routes through floating archipelago islands using wind fans, cloud trampolines, and acceleration crystals.',
    learningObjectives: ['Spatial Route Planning', 'Algorithmic Sequencing', 'Aerodynamic Logic', 'Resource Budgeting'],
    keyMechanics: ['Track Tile Grid', 'Air Current Physics Launch', 'Sky Beacon Docking'],
    estimatedSessionSeconds: 75,
    rankOrder: 8,
  },
  rhythm_spells: {
    id: 'rhythm_spells',
    title: 'Rhythm Spells',
    subtitle: 'Auditory Patterning & Musical Phonics',
    category: 'musical_patterns',
    primaryDomain: 'phonics',
    secondaryDomains: ['memory'],
    icon: '🎵',
    route: '/playground/rhythm-spells',
    ageRange: { min: 4, max: 10 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #134e4a 0%, #0d9488 50%, #2dd4bf 100%)',
    accentGlow: 'rgba(13, 148, 136, 0.5)',
    description: 'Echo musical rhythms and complete syllable beat patterns on pentatonic rune drums to cast dazzling harmonic sound spells.',
    learningObjectives: ['Syllabic Rhythm Phonics', 'Auditory Patterning', 'Mathematical Fractions', 'Beat Synchronization'],
    keyMechanics: ['Rune Drum Tap', 'Pentatonic Micro-Scheduling', 'Visual Ripple Harmonics'],
    estimatedSessionSeconds: 45,
    rankOrder: 9,
  },
  time_machine: {
    id: 'time_machine',
    title: 'Time Machine',
    subtitle: 'Causal Sequencing & Chronological Riddles',
    category: 'temporal_reasoning',
    primaryDomain: 'comprehension',
    secondaryDomains: ['logic', 'memory'],
    icon: '⏳',
    route: '/playground/time-machine',
    ageRange: { min: 5, max: 11 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #713f12 0%, #b45309 50%, #fbbf24 100%)',
    accentGlow: 'rgba(180, 83, 9, 0.5)',
    description: 'Scrub the Chrono-Dial to assemble scrambled past, present, and future events, watching life cycles and ruins transform in real-time.',
    learningObjectives: ['Narrative Chronology', 'Causal Reasoning', 'Scientific Life Cycles', 'Prediction'],
    keyMechanics: ['Timeline Card Assembly', 'Smooth Chrono-Slider Scrubbing', 'Animated Evolution'],
    estimatedSessionSeconds: 60,
    rankOrder: 10,
  },
  orbis_quest_run: {
    id: 'orbis_quest_run',
    title: 'ORBis Quest Run',
    subtitle: 'Side-Scrolling Platformer & Micro-Challenges',
    category: 'adventure_action',
    primaryDomain: 'comprehension',
    secondaryDomains: ['memory', 'logic'],
    icon: '🏃',
    route: '/playground/quest-run',
    ageRange: { min: 5, max: 11 },
    status: 'in_development',
    isPlayable: false,
    heroBannerColor: 'linear-gradient(135deg, #881337 0%, #e11d48 50%, #fda4af 100%)',
    accentGlow: 'rgba(225, 29, 72, 0.5)',
    description: 'Embark on a kinetic adventure runner through magical biomes, overcoming obstacles with rapid-fire micro-learning puzzles.',
    learningObjectives: ['Rapid Pattern Classification', 'Executive Decision Making', 'Reflex Coordination', 'Multidisciplinary Recall'],
    keyMechanics: ['Auto-Run Momentum', 'Checkpoint Micro-Puzzles', 'Hero Crest Collection'],
    estimatedSessionSeconds: 90,
    rankOrder: 11,
  },
}

export function getAllPlaygroundGames(): PlaygroundGameMetadata[] {
  return Object.values(PLAYGROUND_REGISTRY).sort((a, b) => a.rankOrder - b.rankOrder)
}

export function getPlaygroundGame(id: PlaygroundGameId): PlaygroundGameMetadata | undefined {
  return PLAYGROUND_REGISTRY[id]
}

export function getPlayablePlaygroundGames(): PlaygroundGameMetadata[] {
  return getAllPlaygroundGames().filter((game) => game.isPlayable)
}

export function getPlaygroundGamesByDomain(domain: CognitiveDomain): PlaygroundGameMetadata[] {
  return getAllPlaygroundGames().filter(
    (game) => game.primaryDomain === domain || game.secondaryDomains.includes(domain)
  )
}
